### ISSUE TITLE
Feature request: Newline highlighting

### ISSUE THREAD

**Issue by GiovanH** [SublimeText-Markdown/MarkdownEditing#598] opened 2021-04-10 06:49 UTC
In markdown, two spaces followed by a newline indicates a line break without a paragraph break. This is hard to see in editors, and some sort of visual highlight in these cases would be much appreciated.

**Comment by deathaxe** [comment] 2021-05-04 19:06
ST4 can draw those via

```
	"draw_white_space":
	[
		"trailing"
	],
```

**Comment by GiovanH** [comment] 2021-05-05 02:54
> ST4 can draw those via
> 
> ```
> 	"draw_white_space":
> 	[
> 		"trailing"
> 	],
> ```

This is a step in the right direction, but for markdown it's exactly two trailing spaces that need special highlighting, not just "any trailing whitespace".

**Comment by deathaxe** [comment] 2021-05-14 20:20
Duplicate of #470

**Closed** 2021-05-14 20:20 UTC
Labels: duplicate
