### ISSUE TITLE
link text very dark

### ISSUE THREAD

**Issue by zachvalenta** [SublimeText-Markdown/MarkdownEditing#526] opened 2018-06-08 15:08 UTC
link text used to be bright yellow, now dark to the point of unreadable

Sublime version: 3.1.1, build 3176

![screen shot 2018-06-08 at 11 06 46 am](https://user-images.githubusercontent.com/11388735/41165683-3fab417c-6b0c-11e8-9fe5-80c612c55838.png)

**Comment by felixhao28** [comment] 2018-06-11 08:47
I reverted all the way back to 4023d394d669049504273dfcc1e9b985b3508f05 when ArkDark theme was firstly added and still cannot see "link text used to be bright yellow".

**Comment by zachvalenta** [comment] 2018-06-12 15:48
this is how raw link text used to be displayed, in yellow

<img width="683" alt="screen shot 2018-06-12 at 11 46 22 am" src="https://user-images.githubusercontent.com/11388735/41301613-71a2169c-6e36-11e8-9e8a-7ce7dcbf2a13.png">

**Comment by felixhao28** [comment] 2018-06-13 04:45
Yes I can confirm the issue. It is probably a bug in Sublime Text but I somehow worked around it by switching to ST's new color scheme file format. The fix will go live on the next update.

**Comment by felixhao28** [comment] 2018-06-14 02:34
Oh don't close it just yet. The issue is still there. Keeping it open will help others know about the issue so they won't open new ticket. It will be closed after the next patch releases.

**Comment by zachvalenta** [comment] 2018-06-14 10:53
good idea! new to OSS :)

**Closed** 2021-01-19 07:19 UTC
