### ISSUE TITLE
Bug I don't understand :(

### ISSUE THREAD

**Issue by kud** [SublimeText-Markdown/MarkdownEditing#554] opened 2019-02-27 14:45 UTC
<img width="532" alt="image" src="https://user-images.githubusercontent.com/655838/53498462-ae9cbb00-3aa6-11e9-9a74-4320b60296fa.png">

**Comment by kud** [comment] 2019-02-27 14:56
https://github.com/borela/naomi

**Comment by janiosarmento** [comment] 2019-04-15 14:13
I don't use Naomi, and right now I'm facing the very same error.

**Comment by felixhao28** [comment] 2019-04-26 05:01
Closing as a duplicate of #533

**Closed by felixhao28** 2019-04-26 05:01 UTC
