### ISSUE TITLE
Is there a keyboard shortcut for toggling GFM tasklist items done/undone

### ISSUE THREAD

**Issue by dahanbn** [SublimeText-Markdown/MarkdownEditing#462] opened 2017-09-08 05:59 UTC
I was just wondering what is the best way to toggle the status of GFM tasklist items from `[ ]` (open) to `[X]` (done) or in the other direction. 

Has MarkdownEditing a builtin function for that?

**Comment by felixhao28** [comment] 2018-02-05 09:19
No. There are some related discussions in #239

**Comment by deathaxe** [comment] 2021-07-25 15:57
Duplicate of #589

**Closed by deathaxe** 2021-07-25 15:57 UTC
