### ISSUE TITLE
Markdown format characters don't follow words for line breaks

### ISSUE THREAD

**Issue by Ductapemaster** [SublimeText-Markdown/MarkdownEditing#423] opened 2017-02-27 18:50 UTC
I've been writing a lot of notes in markdown recently and I realized that the line break behavior when using formatting characters is a bit odd.  

The heart is the issue is that the formatting characters do not line break with the attached words (which only happens in the first and last word of a formatted string).  The issue is clearly demonstrated in the following screenshots:

![incorrect1](https://cloud.githubusercontent.com/assets/3271295/23374700/38475dcc-fcda-11e6-8417-5e813586be7f.PNG)
![incorrect2](https://cloud.githubusercontent.com/assets/3271295/23374701/3848641a-fcda-11e6-9cfa-31e05e131703.PNG)

In both of these cases, I would expect the formatting underscores (or any other formatting character) to follow the word that they are attached to so you don't have dangling formatters on another line.

Is this something that can be fixed in the extension, or is it deep in ST?

**Comment by felixhao28** [comment] 2017-03-01 02:47
It has something to do with the grammar definition which separates the underscores from the actual text inside to apply different styles. Maybe it can be improved but I am avoiding changing the grammar file before #324.

**Comment by Ductapemaster** [comment] 2017-03-03 01:20
No problem, thank you!

**Comment by deathaxe** [comment] 2021-07-27 16:11
Indeed a duplicate of #395

**Closed by deathaxe** 2021-07-27 16:11 UTC
Labels: C: ST issue
