### ISSUE TITLE
Emoji Colors inverted

### ISSUE THREAD

**Issue by EyMaddis** [SublimeText-Markdown/MarkdownEditing#441] opened 2017-06-04 22:45 UTC
Hi, 
thanks for the great plugin!
I just noticed that the colors of emojis like ✅ are inverted.
![image](https://cloud.githubusercontent.com/assets/1409100/26765997/0b04de52-4988-11e7-85b1-bfad245e7928.png)

I am on MacOS Sierra, Sublime Text 3 Build 3126 using the default Markdown mode and light theme.

**Comment by felixhao28** [comment] 2017-06-16 04:26
![image](https://user-images.githubusercontent.com/2417391/27211869-e469f1dc-528e-11e7-8ed8-9fef87803a8c.png)

It looks fine on my side. Maybe it's a mac specific issue?

**Comment by azriel91** [comment] 2017-08-08 10:51
I'm on Mac (OS X) and I can confirm I see them inverted as well. I don't have a Windows / Linux box currently to check on those.

**Comment by azriel91** [comment] 2017-08-09 08:52
Just discovered, when I opened sublime with the file previously open, it renders fine:
<img width="170" alt="before_editing" src="https://user-images.githubusercontent.com/2993230/29113169-9fb34840-7cf0-11e7-8be0-371460198082.png">

But once I started editing the file, it became inverted:
<img width="155" alt="begin_editing" src="https://user-images.githubusercontent.com/2993230/29113212-bee3161e-7cf0-11e7-8020-89239eca7770.png">

Closing and reopening the tab still gives me the inverted colours.

**Comment by felixhao28** [comment] 2017-08-09 09:35
Does this only happen to markdown files? Only with MDE installed?

**Comment by azriel91** [comment] 2017-08-09 09:40
No it happens with any syntax highlighting (and plain text as well) &mdash; with both MDE installed and uninstalled &mdash; so sounds like an upstream issue

**Comment by felixhao28** [comment] 2017-08-09 09:46
Looks like a known issue since 2014 😏 

https://github.com/SublimeTextIssues/Core/issues/214

**Closed** 2021-05-14 20:21 UTC
Labels: C: ST issue, wontfix
