### ISSUE TITLE
Tilde in links break syntax highlighting

### ISSUE THREAD

**Issue by stevenxxiu** [SublimeText-Markdown/MarkdownEditing#677] opened 2022-01-06 13:58 UTC
The following valid *Markdown* isn't highlighted correctly. *MarkdownEditing* thinks there's a strikethrough:

    [filenames - Make pwd result in terms of "~"? - Unix & Linux Stack Exchange](https://unix.stackexchange.com/questions/207210/make-pwd-result-in-terms-of/207214#207214)

**Comment by deathaxe** [comment] 2022-01-06 16:50
More or less a duplicate of #637

**Comment by stevenxxiu** [comment] 2022-01-07 00:24
Thanks, the comment https://github.com/SublimeText-Markdown/MarkdownEditing/issues/637#issuecomment-929835517 worked for me.

**Closed** 2022-01-14 18:52 UTC
