### ISSUE TITLE
Headings Levels keybinding on macOS not working…  and other things

### ISSUE THREAD

**Issue by luispuerto** [SublimeText-Markdown/MarkdownEditing#644] opened 2021-09-21 20:19 UTC
Hey! 

I really don't know if it's since the last version of since 3.0 but the keybindings on macOS for headings aren't working.

**Comment by luispuerto** [comment] 2021-09-22 07:57
I had to remove 

```
"context":
		[
			{ "key": "selector", "operator": "equal", "operand": "text.html.markdown - meta.frontmatter - meta.disable-markdown - markup.raw", "match_all": true },
			{ "key": "mde.keymap_disable.set_heading_level", "operand": false }
		]
```

from the keybinding to make it work. Also the keybindings for mac are wrong? 

They are defined as: 

```
{ "keys": ["ctrl+alt+."], "command": "mde_change_headings_level", "args": {"by": 1}, "context":
		[
			{ "key": "selector", "operator": "equal", "operand": "text.html.markdown - meta.frontmatter - meta.disable-markdown - markup.raw", "match_all": true },
			{ "key": "mde.keymap_disable.set_heading_level", "operand": false }
		]
},
{ "keys": ["ctrl+alt+,"], "command": "mde_change_headings_level", "args": {"by": -1}, "context":
		[
			{ "key": "selector", "operator": "equal", "operand": "text.html.markdown - meta.frontmatter - meta.disable-markdown - markup.raw", "match_all": true },
			{ "key": "mde.keymap_disable.set_heading_level", "operand": false }
		]
},
```

So the keybindings are `"ctrl+alt+,"` and `"ctrl+alt+."` while on your [documentation](https://sublimetext-markdown.github.io/MarkdownEditing/usage/#headings-levels) is said that for mac are `⌘ + ^ + .` and `⌘ + ^ + ,`

Another interesting thing is… increasing only goes up to level 5, you can't reach level 6. After a 5 `#` are added it returns to zero. I really don't know if this is correct. I would like to add as `#` I pleases. I know that markdown only "supports" 6 levels. Funnily enough I can only reach level 6 with the command palette… 😤

**Comment by luispuerto** [comment] 2021-09-22 07:59
Gosh! the headings are totally messed up! if there are more than 6 i can't literally do anything with it. I can even delete then!

**Comment by luispuerto** [comment] 2021-09-22 14:42
The Organize References keybinding was not working also and I have to crate a custom one without the 

```
, "context":
		[
			{ "key": "selector", "operator": "equal", "operand": "text.html.markdown", "match_all": true },
			{ "key": "setting.mde.keymap_disable.reference_organize", "operator": "not_equal", "operand": true }
		]
```

Am I missing some config that is making those bindings not work?

**Comment by deathaxe** [comment] 2021-09-22 16:00
1. Missing `settings.` is already addressed by https://github.com/SublimeText-Markdown/MarkdownEditing/pull/642/commits/787c8afd5f039a5681121b32540b38363d10b510
2. Markdown specification supports heading levels 1..6. This is what syntax definition and all other functions are designed for.

see: https://spec.commonmark.org/0.30/#atx-headings

**Comment by luispuerto** [comment] 2021-09-22 17:32
> 1. Missing `settings.` is already addressed by https://github.com/SublimeText-Markdown/MarkdownEditing/pull/642/commits/787c8afd5f039a5681121b32540b38363d10b510

Great!! Looking forward for the solution to be published 

> 2. Markdown specification supports heading levels 1..6. This is what syntax definition and all other functions are designed for.

Fair enough, but increasing one by one I just can reach level 5, not level 6.

**Comment by deathaxe** [comment] 2021-09-22 17:45
> Fair enough, but increasing one by one I just can reach level 5, not level 6.

Too easy to miss such details in such a mess of comments.

**Comment by deathaxe** [comment] 2021-09-22 17:50
> So the keybindings are `"ctrl+alt+,"` and `"ctrl+alt+."` while on your documentation is said that for mac are `⌘ + ^ + .` and `⌘ + ^ + ,`

Without any Apple product in range I do my best to keep up with their strange key symbols and ST's way of naming them. Some of those bindings may even be untouched and have just been copied from the old README.

PRs with corrections or improvements are welcome.

**Comment by luispuerto** [comment] 2021-09-22 17:51
> Too easy to miss such details in such a mess of comments.

Sorry 😆  posted while discovering the issues. Not really sure if the problem was just mine.

**Closed** 2021-09-26 15:48 UTC
Labels: C: plugins, C: key bindings, bug

**Comment by luispuerto** [comment] 2021-09-26 18:12
Hey! Now it works, but whether the defined keybinding on the settings is wrong or it's the documentation. Per documentation on macOS the keybinding should be `⌘ + ^ + .` and `⌘ + ^ + ,`, but now they are `⎇ + ^ + .` and `⎇ + ^ + ,`.

**Comment by deathaxe** [comment] 2021-09-26 21:05
Yes, it used to be `super+alt+.`. Will add that to the next bugfix

**Comment by luispuerto** [comment] 2021-11-11 11:35
I think you've mess with this again…

**Comment by deathaxe** [comment] 2021-11-11 15:39
As I had to change it on Windows/Linux, I decided to use the same binding on all OS. Docs are updated and bindings won't be changed once again.

**Comment by luispuerto** [comment] 2021-11-11 18:26
Ok!
Anyhow on the command palette que shortcuts doesn't show up correctly. 

<img width="568" alt="image" src="https://user-images.githubusercontent.com/22882880/141349949-d1559488-e5c4-4078-9199-cbe54874cb34.png">

**Comment by deathaxe** [comment] 2021-11-12 16:13
Seems to be caused by order of key bindings. The `delete` key is bound to that command to keep closing hashs balanced in case a leading hash is deleted. Seems the restricted context is not respected by command palette but only the order of rules.

**Comment by luispuerto** [comment] 2021-11-13 14:33
I fix it adding to keybinding to my custom keybinding.

**Comment by Jmuccigr** [comment] 2022-03-20 15:04
I can't get these to work (either). Version 3.1.1 on Sublimetext build 4126.

First, the default on my system uses alt-#, which equates to option-#, but those are a no-no according to [this doc](https://docs.sublimetext.io/reference/key_bindings.html#the-any-character-binding) (they conflict with standard non-ASCII characters).

I tried changing them to use control-# instead or super-control, but neither works for me.

shift-alt-, and shift-alt-. both do work to decrease and increase heading level, respectively.
