### ISSUE TITLE
Conflict with in-built spell-check

### ISSUE THREAD

**Issue by orschiro** [SublimeText-Markdown/MarkdownEditing#231] opened 2015-02-17 10:55 UTC
Hi, 

There seems to be a conflicting issue with MarkdownEditing and the in-built spell-check. It underlines properly spelled words. Example:

![](https://cloud.githubusercontent.com/assets/170947/6215044/503287ca-b5fd-11e4-8f14-0d2f59e1359a.png)

The issue has been also discussed here:
https://github.com/mangecoeur/AcademicMarkdown/issues/9

Do you have any idea what could cause the issue?

Thankfully,

Robert

**Comment by felixhao28** [comment] 2015-02-26 01:59
![image](https://cloud.githubusercontent.com/assets/2417391/6384900/faa373ca-bd9d-11e4-8ffb-7b4a964d9088.png)

I cannot reproduce the issue. Maybe it is only related to AcademicMarkdown?

**Comment by wesbos** [comment] 2015-07-02 18:21
I have this issue as well. Any time there is a word in square brackets, spell check marks it as incorrect:

![](http://wes.io/bqsm/content)

**Comment by felixhao28** [comment] 2015-07-03 01:31
@wesbos Which build of ST3 are you using? ST3 claims to have fixed this issue in [Build 3080](http://www.sublimetext.com/3) on March 24.

**Comment by wesbos** [comment] 2015-07-03 13:08
@felixhao28 3094 - dev version

**Comment by felixhao28** [comment] 2015-07-04 10:26
@wesbos Yes I can confirm this bug in 3094. It seems to be a regression in the latest patches.

**Comment by wesbos** [comment] 2015-07-04 16:05
Shall I make a forum post for Jon to see?

**Comment by felixhao28** [comment] 2015-07-05 08:59
@wesbos It seems this issue has already been posted on the official forum.

http://www.sublimetext.com/forum/viewtopic.php?f=3&t=18771

Let's hope it gets fixed soon. We can keep this issue ticket open for now and close it when you think it is fixed (or given up by Jon).

**Comment by felixhao28** [comment] 2015-12-25 08:58
Further discussion can be made here: https://github.com/SublimeTextIssues/Core/issues/937

Closing this issue since it is not really our bug.

**Closed by felixhao28** 2015-12-25 08:58 UTC
Labels: impossible
