### ISSUE TITLE
Plugin stopped working on Update (both PC and Mac)

### ISSUE THREAD

**Issue by johnathanz** [SublimeText-Markdown/MarkdownEditing#615] opened 2021-09-13 07:36 UTC
Running Sublime Text 4, build 4113 on both PC (Windows 10) and Mac Mojave v10.14.6 (18G9323)

As soon as the plugin was updated, **all of the colorschemes and settings are gone - none of the enhancement added by Markdown Editing is there**

The Settings also look very odd on PC & Mac
* It no longer has the 3 types of markdown supported
* When clicking on `Preference > Package Settings > Markdown editing > Settings`, it opens us Sublime Text Settings (the right pane in the screenshot below) instead of any of the Markdown Settings file

### PC menu screenshot
Plus, what happens when `Preference > Package Settings > Markdown editing > Settings` is clicked
![image](https://user-images.githubusercontent.com/1593039/133042581-2cf1ebe6-b082-4c29-8072-573c3c67f967.png)

### Mac version of plugin - Before update
I took the screenshot 20 min ago while I was reporting this issues on Github, and the plugin updated in the background!

When I switched back to the ST, the Plugin broke right away.

<img width="984" alt="ST Markdown Editing Plugin - Mac" src="https://user-images.githubusercontent.com/1593039/133042658-82d16826-578d-469d-a5f8-3d3d072c8023.png">

### Mac version of plugin - After Update
![CleanShot 2021-09-13 at 17 42 28](https://user-images.githubusercontent.com/1593039/133043874-bea2f3cd-c5a9-4358-8abe-73d0c5b01704.png)

Let us know what we can do to help with testing the fix!

**Comment by plakhin** [comment] 2021-09-13 11:45
#614 looks related

**Comment by SethArchambault** [comment] 2021-09-13 12:24
Any hack we can do to fix this in the meantime?  My entire note taking system is built on being able to tap a button and quickly navigation to a header (#) so this is going to greatly challenge my productivity until it's resolved.. Thanks!

**Comment by plakhin** [comment] 2021-09-13 12:28
> Any hack we can do to fix this in the meantime? My entire note taking system is built on being able to tap a button and quickly navigation to a header (#) so this is going to greatly challenge my productivity until it's resolved.. Thanks!

https://sublimetext-markdown.github.io/MarkdownEditing/troubleshooting/#roll-back-to-an-older-version

**Comment by Kshitiz-Sharma** [comment] 2021-09-13 13:06
> 
> 
> > Any hack we can do to fix this in the meantime? My entire note taking system is built on being able to tap a button and quickly navigation to a header (#) so this is going to greatly challenge my productivity until it's resolved.. Thanks!
> 
> https://sublimetext-markdown.github.io/MarkdownEditing/troubleshooting/#roll-back-to-an-older-version

The page mentions downloading an older release and following the manual installation guide. But the link to manual installation seems to be broken. Does anyone know where it is?

**Comment by prolinuxua** [comment] 2021-09-13 14:57
The same problem on Linux

**Comment by deathaxe** [comment] 2021-09-13 16:24
The only strange thing about the screenshots is the missing `Select Color Scheme` command, which indicates the plugins to not have been loaded. Any error messages in console?

I am running 3.0.0 on ST4x for quite some time and even had no problems with upgrading or installing on Windows.

Commands keep missing even after restarting ST?

Notes:

1. It uses ST's side-by-side settings view to display preferences, so less items
2. It only provides Markdown and MultiMarkdown syntax, which both support GFM and various other extensions (except Latex due to an oversight). Both are basically bleeding edge ST4 default markdown with some tweaks (more fenced code block syntaxes, kbd tag highlgihting and support for json/coffeescript in frontmatter.

The old syntaxes suffered too many issues and where heavily out-dated. Shipped color schemes have been adjusted so you shouldn't see any difference. If so, please file a dedicated bug, so I can look into.

**Comment by azriel91** [comment] 2021-09-13 21:32
> Commands keep missing even after restarting ST?

Yeap, I've got these error messages in the sublime text console (I'm on a Mac):

```bash
Package Control: The syntax "Packages/MarkdownEditing/Markdown.sublime-syntax" no longer exists
Package Control: The color scheme "Packages/MarkdownEditing/MarkdownEditor-Dark.tmTheme" no longer exists
reloading settings Packages/User/Preferences.sublime-settings

error: Error loading colour scheme Packages/MarkdownEditing/MarkdownEditor-Dark.tmTheme: Unable to open Packages/MarkdownEditing/MarkdownEditor-Dark.tmTheme
# about 30 of these

Unable to open /Users/azrielh/Library/Application Support/Sublime Text/Packages/MarkdownEditing/Preferences.sublime-settings
Unable to open /Users/azrielh/Library/Application Support/Sublime Text/Packages/MarkdownEditing/README.md
```

If I open `"$HOME/Library/Application Support/Sublime Text/Packages/User/Markdown.sublime-settings"`, and comment out the `color_scheme` setting, I can at least now set file syntax to `Markdown` without getting the error pop up, but the commands are still missing.

`${HOME}/Library/Application Support/Sublime Text/Installed Packages/MarkdownEditing.sublime-package` does exist:

```
md5sum "${HOME}/Library/Application Support/Sublime Text/Installed Packages/MarkdownEditing.sublime-package"
b44a3c7fa7d9e6304b3db23b5555ed21  /Users/azrielh/Library/Application Support/Sublime Text/Installed Packages/MarkdownEditing.sublime-package
```

**Comment by azriel91** [comment] 2021-09-13 22:28
On Linux, these are the logs I get when disabling then re-enabling MarkdownEditing:

```
reloading plugin MarkdownEditing.plugin
Traceback (most recent call last):
  File "/opt/sublime_text/Lib/python38/sublime_plugin.py", line 419, in load_module
    m.plugin_loaded()
  File "/home/azriel/.config/sublime-text-3/Installed Packages/MarkdownEditing.sublime-package/plugin.py", line 113, in plugin_loaded
    on_after_install()
  File "/home/azriel/.config/sublime-text-3/Installed Packages/MarkdownEditing.sublime-package/plugins/bootstrap.py", line 74, in on_after_install
    select_color_scheme()
  File "/home/azriel/.config/sublime-text-3/Installed Packages/MarkdownEditing.sublime-package/plugins/color_schemes.py", line 24, in select_color_scheme
    "characters": sublime.load_resource(
  File "/opt/sublime_text/Lib/python38/sublime.py", line 436, in load_resource
    raise FileNotFoundError(f'resource "{name}" not found')
FileNotFoundError: resource "Packages/MarkdownEditing/schemes/Preview.md" not found
reloading settings Packages/User/Preferences.sublime-settings
generating meta info summary
error parsing lexer: Packages/User/MarkdownEditing.sublime-syntax: Error trying to parse sublime-syntax: %YAML indicator is required in Packages/User/MarkdownEditing.sublime-syntax:1:1
generating syntax summary
reloading settings Packages/User/Preferences.sublime-settings
```

Tried creating the `Preview.md` in both the sublime text installation dir, as well as the user config dir, but neither got the error to go away.

I also installed python 3.8.12, because when trying a manual git clone install, there's a python version file that says 3.8, but that didn't help either.

**Comment by deathaxe** [comment] 2021-09-14 15:56
> `Package Control: The syntax "Packages/MarkdownEditing/Markdown.sublime-syntax" no longer exists`
> `Package Control: The color scheme "Packages/MarkdownEditing/MarkdownEditor-Dark.tmTheme" no longer exists`

Syntax was moved to a sub directory and color schemes are converted to new sublime-color-scheme format.

Syntax and color scheme should have been reassigned automtically. I guess most of that trouble during update was caused by the switch from python 3.3 to python 3.8 plugin host.

Otherwise it may happen you need to remove some syntax specific settings. Except color scheme none will be touched automatically.  That's what upgrade message was about (if it was displayed). 

> Unable to open /Users/azrielh/Library/Application Support/Sublime Text/Packages/MarkdownEditing/README.md

Strange: README is not opened automatically at any point anymore. It used to be the case after installing in 2.x, but this is no longer the case.

The package is installed into _Installed Packages/MarkdownEditing.sublime-package_. Maybe some parts of the old version keep existing in _Packages/MarkdownEditing_ folder?

> On Linux, these are the logs I get when disabling then re-enabling MarkdownEditing:

Does _Preview.md_ exist and filename have correct case in _Installed Packages/MarkdownEditing.sublime-package/schemes_? The package is basically a zip file.

**Comment by deathaxe** [comment] 2021-09-14 16:17
Maybe Preview.md not being found is a timing issue as the function is called directly after plugin host is ready. Will add a little delay to see whether it helps.

**Comment by azriel91** [comment] 2021-09-14 19:36
Update, the plugin started working on Linux, though I'm not sure if I did anything relevant. Potential actions:

* Restarted computer
* Closed every tab that used to have the GFM syntax (I copied the contents, pasted to a new tab with Plain Text syntax highlighting)
* Set syntax to Markdown (based on reading one of the other issues).

There's only this error in the console:

```
error parsing lexer: Packages/User/MarkdownEditing.sublime-syntax: Error trying to parse sublime-syntax: %YAML indicator is required in Packages/User/MarkdownEditing.sublime-syntax:1:1
```

That last one may be because one of my tabs has a `` ```yaml`` block

**Comment by deathaxe** [comment] 2021-09-14 20:32
Plugins run on ST's plugin host. It doesn't depend on any external python interpreter.

The error message about MarkdownEditing.sublime-syntax should disappear with upgrade to 3.0.2. I just choose a stupid file name by accident. It should have been a sublime-settings file. You can remove it manually, too.

**Comment by johnathanz** [comment] 2021-09-15 16:45
It looks like it was a python plugin 3.3 -> 3.8 upgrade issue.

I had these lines in my startup console message:
```
reloading python 3.3 plugin 0_package_control_loader.00-package_control
reloading python 3.3 plugin 0_package_control_loader.01-pygments
reloading python 3.3 plugin 0_package_control_loader.50-pymdownx
reloading python 3.3 plugin 0_package_control_loader.50-python-markdown
reloading python 3.3 plugin 0_package_control_loader.50-pyyaml
reloading python 3.3 plugin 0_package_control_loader.51-bs4
reloading python 3.3 plugin Colorsublime.colorsublime-plugin
```

I completely removed ST4, and reinstalled all packages.

It's all working now.

Thanks for the update @deathaxe .  File type (markdown) and being able to control the markdown files color via command palette are wonderful!

Appreciate your hard work!

**Comment by johnathanz** [comment] 2021-09-17 17:16
Thanks @deathaxe . To help me help myself, are the list of setting documented anywhere?

**Comment by deathaxe** [comment] 2021-09-17 18:43
The settings on the left when using `Preferences: MarkdownEditing Settings` have short comments. But it's probably hard for them to answer such special questions.

**Closed** 2021-09-19 13:08 UTC
