### ISSUE TITLE
Organize references is not working properly

### ISSUE THREAD

**Issue by luispuerto** [SublimeText-Markdown/MarkdownEditing#674] opened 2021-12-17 12:44 UTC
Mentions references a correctly defined as ones with an error

<img width="453" alt="Screen Shot 2021-12-17 at 13 39 44" src="https://user-images.githubusercontent.com/22882880/146546538-0a45537d-e2db-4b06-86aa-3c90da86f94a.png">

**Comment by deathaxe** [comment] 2022-01-22 12:19
This issue may be caused by or related with the contet of the brackets. I can't reproduce it

**Comment by luispuerto** [comment] 2022-01-22 14:00
<img width="819" alt="Screen Shot 2022-01-22 at 15 00 34" src="https://user-images.githubusercontent.com/22882880/150641391-cab763af-3752-41c3-b928-eeba67a5cd83.png">

**Comment by luispuerto** [comment] 2022-01-22 14:01
What do you mean??? It happens to me with any content 

<img width="819" alt="Screen Shot 2022-01-22 at 15 01 25" src="https://user-images.githubusercontent.com/22882880/150641425-88acf44f-e617-4045-bba2-67fd5fde5be7.png">

**Comment by deathaxe** [comment] 2022-01-22 14:17
It's working well here using MDE 3.1.0 / ST4126 on Windows

![grafik](https://user-images.githubusercontent.com/16542113/150641982-9df022e3-ae09-434b-a860-6af15da96525.png)

**Comment by luispuerto** [comment] 2022-01-22 14:41
OK! 

It seems that the problem comes from using the [markdown extended systax](https://github.com/jonschlinkert/sublime-markdown-extended)… Which haven't been updated in 5 years. 🤣

**Comment by luispuerto** [comment] 2022-01-22 15:07
By the way, this worked perfectly before, so I guess it has to do something with the 3.1 update. It would be really great if we can make it work, since I really like how markdown extended works. It's mainly relate to the color scheme.

**Comment by deathaxe** [comment] 2022-01-22 17:47
As MDE's syntax is improved more and more functions will start making use of it in order to reduce the amout of error prone and limited regexp parsing to identify all the different entities. It's just that ST's syntax engine can parse Markdown more efficiently and reliably including various edge cases.

If you like certain aspects of Markdown Extended syntax, we might try to integrate them into MDE, but at some point MDE's functions won't work with different syntax definition being used.

**Comment by deathaxe** [comment] 2022-01-23 09:08
Closing it as invalid, because it's working perfectly with the syntax definition provided by this package.

**Closed by deathaxe** 2022-01-23 09:08 UTC
