### ISSUE TITLE
Github Flavored Markdown option missing from MarkdownEditing syntax list

### ISSUE THREAD

**Issue by HybridEyeGrillage** [SublimeText-Markdown/MarkdownEditing#630] opened 2021-09-15 14:55 UTC
Hi! I've been using MarkdownEditing for  awhile and just a few days ago, my preferred flavor had disappeared from my syntax list options:
![image](https://user-images.githubusercontent.com/5670441/133457015-6024162d-4b08-49c3-ba30-3ee233cf4235.png)

I'm using Sublime Text 3 v3.2.2, Build 3211 (latest from the 3.x).

I've tried deleting and reinstalling the package through Package Control, but it still isn't there. 
I'm assuming from the README that this flavor is still an option, right?
Does anyone know why this has happened?

**Comment by deathaxe** [comment] 2021-09-15 15:48
Duplicate of #614

**Closed by deathaxe** 2021-09-15 15:48 UTC
