### ISSUE TITLE
hangs when opening a markdown file in build 3124

### ISSUE THREAD

**Issue by mderazon** [SublimeText-Markdown/MarkdownEditing#390] opened 2016-09-22 11:10 UTC
Recently upgraded ST to build 3124 and no longer able to open markdown files.

After uninstalling this, works fine

**Comment by ianchanning** [comment] 2016-09-22 13:28
I found this isn't strictly true, some markdown files were ok, others not. This is causing problems with quite a few people: https://forum.sublimetext.com/t/sublime-3124-eat-up-my-cpus/23016

My 4000+ line long `todo.md` file opens fine.

The below acorn globals markdown text in a `README.md` file which comes in the acorn-globals npm module causes a complete freeze of ST when I try to switch it to the Markdown GFM syntax. Opening the console before switching to the Markdown GFM doesn't show anything. ST just freezes.

![2016-09-22 15_23_38-](https://cloud.githubusercontent.com/assets/233318/18749769/a44b11b8-80d8-11e6-9cc2-6837278e70a2.png)

I did get the following in the console from when I tried to open the file directly:

![2016-09-22 14_46_27-program manager](https://cloud.githubusercontent.com/assets/233318/18749870/0f58e3ae-80d9-11e6-8504-ceeaa0a0f309.png)



---

# acorn-globals

Detect global variables in JavaScript using acorn

[![Build Status](https://img.shields.io/travis/ForbesLindesay/acorn-globals/master.svg)](https://travis-ci.org/ForbesLindesay/acorn-globals)
[![Dependency Status](https://img.shields.io/david/ForbesLindesay/acorn-globals.svg)](https://david-dm.org/ForbesLindesay/acorn-globals)
[![NPM version](https://img.shields.io/npm/v/acorn-globals.svg)](https://www.npmjs.org/package/acorn-globals)

## Installation

    npm install acorn-globals

## Usage

detect.js

```js
var fs = require('fs');
var detect = require('acorn-globals');

var src = fs.readFileSync(__dirname + '/input.js', 'utf8');

var scope = detect(src);
console.dir(scope);
```

input.js

```js
var x = 5;
var y = 3, z = 2;

w.foo();
w = 2;

RAWR=444;
RAWR.foo();

BLARG=3;

foo(function () {
    var BAR = 3;
    process.nextTick(function (ZZZZZZZZZZZZ) {
        console.log('beep boop');
        var xyz = 4;
        x += 10;
        x.zzzzzz;
        ZZZ=6;
    });
    function doom () {
    }
    ZZZ.foo();

});

console.log(xyz);
```

output:

```
$ node example/detect.js
[ { name: 'BLARG', nodes: [ [Object] ] },
  { name: 'RAWR', nodes: [ [Object], [Object] ] },
  { name: 'ZZZ', nodes: [ [Object], [Object] ] },
  { name: 'console', nodes: [ [Object], [Object] ] },
  { name: 'foo', nodes: [ [Object] ] },
  { name: 'process', nodes: [ [Object] ] },
  { name: 'w', nodes: [ [Object], [Object] ] },
  { name: 'xyz', nodes: [ [Object] ] } ]
```


## License

  MIT

**Comment by ianchanning** [comment] 2016-09-22 13:54
Further to the above here's the text I get after eventually ST unfroze:

```
Error loading scope:source.tsx: Unable to find syntax file for scope source.tsx in Packages/MarkdownEditing/Markdown.tmLanguage
Error loading scope:source.scss: Unable to find syntax file for scope source.scss in Packages/MarkdownEditing/Markdown.tmLanguage
Error loading scope:source.coffee: Unable to find syntax file for scope source.coffee in Packages/MarkdownEditing/Markdown.tmLanguage
Error loading scope:source.scheme: Unable to find syntax file for scope source.scheme in Packages/MarkdownEditing/Markdown.tmLanguage
Error loading scope:source.swift: Unable to find syntax file for scope source.swift in Packages/MarkdownEditing/Markdown.tmLanguage
Error loading scope:source.sass: Unable to find syntax file for scope source.sass in Packages/MarkdownEditing/Markdown.tmLanguage
Error loading scope:source.ts: Unable to find syntax file for scope source.ts in Packages/MarkdownEditing/Markdown.tmLanguage
rule scope:source.scala#xml-comments has a scope name, but is unreachable, so the name will never be used

**Comment by wbond** [comment] 2016-09-22 15:55
Yes, the Markdown GFM syntax does seem like it is causing performance issues for lots of users. I'm going to dig in and see what I can come up with.

**Comment by alexkadis** [comment] 2016-09-22 16:10
My console errors:

` Error loading scope:source.tsx: Unable to find syntax file for scope source.tsx in Packages/MarkdownEditing/Markdown.tmLanguage
Error loading scope:source.scss: Unable to find syntax file for scope source.scss in Packages/MarkdownEditing/Markdown.tmLanguage
Error loading scope:source.coffee: Unable to find syntax file for scope source.coffee in Packages/MarkdownEditing/Markdown.tmLanguage
Error loading scope:source.less: Unable to find syntax file for scope source.less in Packages/MarkdownEditing/Markdown.tmLanguage
Error loading scope:source.scheme: Unable to find syntax file for scope source.scheme in Packages/MarkdownEditing/Markdown.tmLanguage
Error loading scope:source.swift: Unable to find syntax file for scope source.swift in Packages/MarkdownEditing/Markdown.tmLanguage
Error loading scope:source.ts: Unable to find syntax file for scope source.ts in Packages/MarkdownEditing/Markdown.tmLanguage
rule scope:source.scala#xml-comments has a scope name, but is unreachable, so the name will never be used`

**Comment by Kristinita** [comment] 2016-09-22 16:15
I have same stack trace in Build 3114, see [my comment](https://github.com/jonschlinkert/sublime-markdown-extended/issues/125#issuecomment-245666877).

Thanks.

**Comment by djspiewak** [comment] 2016-09-22 16:34
@wbond I wonder if it's an interaction with one of the updated modes.  I can rule out Scala, since I've been using the Markdown GFM syntax with the dev builds all along and not had any performance problems at all (that I've noticed, anyway).  I basically never embed fenced snippets that *aren't* Scala though, so it may be an interaction with one of the others (like JavaScript).

**Comment by wbond** [comment] 2016-09-22 16:49
This will cause a hang, and adding `rsion` after the `--ve` will hang for much longer.

    ```javascript
    var version = exec('node --ve', {silent:true}).stdout;
    ```

It seems as though some catastrophic backtracking is happening somewhere.

**Comment by wbond** [comment] 2016-09-22 17:09
So this is an interaction of patterns in the JavaScript syntax (which only uses sregex, and does not trigger backtracking) and patterns in Markdown GFM that use regex features that fall back to Oniguruma, which does backtracking.

Oniguruma has issues with the changes in https://github.com/sublimehq/Packages/commit/bbc49d9721dfb7f9151062d7422eb9a7a3879647. Most likely the `arrow_func_lookahead`.

**Comment by wbond** [comment] 2016-09-23 18:01
[Dev Build 3125](https://forum.sublimetext.com/t/dev-build-3125/23117) includes a workaround for this.

**Comment by felixhao28** [comment] 2016-09-29 06:55
So this issue no longer repros on Dev Build 3125 right?

**Comment by Kristinita** [comment] 2016-10-01 06:26
[Similar problem](https://github.com/divinites/gissues/issues/19#issuecomment-250895465) for GitHub Issue plugin.

**Comment by felixhao28** [comment] 2016-10-11 09:24
Just for anyone who wonders about error messages like "Unable to find syntax file for scope source.swift", those are expected since those syntax definitions are optionally required. @maliayas and I talked about this here #174.

**Comment by Kristinita** [comment] 2016-10-22 17:15
@felixhao28, problem always reproduced for me, if any Markdown file was opened for me, when I run Sublime Text.

```
Error loading scope:source.tsx: Unable to find syntax file for scope source.tsx in Packages/MarkdownEditing/Markdown.tmLanguage
Error loading scope:source.scss: Unable to find syntax file for scope source.scss in Packages/MarkdownEditing/Markdown.tmLanguage
Error loading scope:source.coffee: Unable to find syntax file for scope source.coffee in Packages/MarkdownEditing/Markdown.tmLanguage
Error loading scope:source.less: Unable to find syntax file for scope source.less in Packages/MarkdownEditing/Markdown.tmLanguage
Error loading scope:source.scheme: Unable to find syntax file for scope source.scheme in Packages/MarkdownEditing/Markdown.tmLanguage
Error loading scope:source.swift: Unable to find syntax file for scope source.swift in Packages/MarkdownEditing/Markdown.tmLanguage
Error loading scope:source.sass: Unable to find syntax file for scope source.sass in Packages/MarkdownEditing/Markdown.tmLanguage
Error loading scope:source.ts: Unable to find syntax file for scope source.ts in Packages/MarkdownEditing/Markdown.tmLanguage
rule scope:source.scala#xml-comments has a scope name, but is unreachable, so the name will never be used
```

The problem is reproduced for me in a version of Sublime Text without plugins and user settings. If neither Markdown file is not open when I run Sublime Text, I no get errors.

Thanks.

**Comment by Kristinita** [comment] 2016-11-23 11:50
Any ideas?

**Comment by felixhao28** [comment] 2016-11-23 15:08
@Kristinita Those errors are expected. They basically mean those code cannot be highlighted since you don't have related syntax plugins installed. I can't suppress them so please ignore.

**Comment by maliayas** [comment] 2016-12-13 20:43
Things look fine with 3125. So I'm closing the issue. Thanks.

**Closed by maliayas** 2016-12-13 20:43 UTC

**Comment by Kristinita** [comment] 2017-01-22 11:50
@maliayas ,

> Things look fine with 3125.

But not for me. Problem is reproduced for me in Sublime Text Build 3126 without plugins and user settings.

Thanks.

**Comment by felixhao28** [comment] 2017-01-22 13:07
@Kristinita those "Error loading..." messages are expected. They don't cause any issue other than appearing on your console.

**Comment by Kristinita** [comment] 2017-01-22 13:09
@felixhao28 

> They don't cause any issue other than appearing on your console.

Yes, I understand, but I don't like «garbage» in my console.

Thanks.

**Comment by duolee** [comment] 2017-06-27 11:16
@Kristinita So there is no solution to these <<garbage>>, just leave them in the console.
I'm also bothered by this problem with Sublime Text build 3126.

**Comment by felixhao28** [comment] 2017-06-28 02:12
If you really want to hide them, you can add required syntax by installing corresponding plugin packages, including TypeScript, Less, Scheme, Swift.

**Comment by duolee** [comment] 2017-06-28 10:16
@felixhao28 Actually I don't know these syntax at all, so I think I'd better ignore the annoying errors in the console now. Maybe I'll install the packages you mentioned later when I have to use them. Anyway, thanks a lot for your advice!

**Comment by wbond** [comment] 2017-06-28 10:18
The "annoying" errors are correct, and won't go away. The syntax is trying to include files you don't have, so it is warning you that the syntax is not going to work as originally intended because files are missing off of your system.

**Comment by gonboy** [comment] 2018-04-18 04:08
source.reason: Unable to find syntax file for scope source.reason

insall which package ?

**Comment by felixhao28** [comment] 2018-04-23 04:39
@gonboy 
[Reason](https://reasonml.github.io/)
[sublime-reason](https://github.com/reasonml-editor/sublime-reason)
