### ISSUE TITLE
WYSIWYG editor?

### ISSUE THREAD

**Issue by axfelix** [SublimeText-Markdown/MarkdownEditing#461] opened 2017-09-05 22:03 UTC
Hi,

I really like this plugin, and I'm very curious about the "WYSIWYG editor" workflow you're describing, but I don't think I'm achieving the desired effect by using LiveReload and MarkdownPreview (I just get a static preview in my browser; I can't tell what LiveReload is supposed to be doing). Can you clarify the instructions and intended outcome? Thanks!

**Comment by felixhao28** [comment] 2017-09-06 07:15
The expected behavior is that whenever you save your changes in markdown file, the webpage then updates it self automatically. It's a feature in [markdown preview](https://github.com/revolunet/sublimetext-markdown-preview) rather than in MDE. I list it here because I find it very useful. You can find more detailed instructions on their pages.

**Comment by felixhao28** [comment] 2017-09-06 07:18
I am closing this issue for now. If you (or anyone reading this) think you are experiencing a bug on WYSIWYG editor, please head over to [markdown preview's issues page](https://github.com/revolunet/sublimetext-markdown-preview/issues) to raise it.

**Closed by felixhao28** 2017-09-06 07:18 UTC
Labels: question
