### ISSUE TITLE
List editing: automatic numbering and indentation does not work

### ISSUE THREAD

**Issue by sport4minus** [SublimeText-Markdown/MarkdownEditing#388] opened 2016-09-06 08:43 UTC
As opposed to the description and my experience with this Plugin for a long time, 
the current version (Package Control Install) has problems when:

1) starting a numbered list: "enter" doesnt create a new list entry anymore

2) indenting a bullet point list: hitting "tab" on an empty list entry (successfully created by hitting "enter") does not indent and change bullet type.

**Comment by nselikoff** [comment] 2016-09-12 19:29
+1 I'm seeing the same issues.

**Comment by felixhao28** [comment] 2016-09-29 09:23
This feature works perfectly fine for me on build 3125. What version of sublime text are you using?

**Comment by sport4minus** [comment] 2016-09-29 10:26
Sorry, i should have mentioned: its Sublime Text 2, Build 2221

**Comment by michou** [comment] 2016-10-06 20:53
Same here with SublimeTest 2, Build 2221, on Ubuntu 14.04

**Comment by dragonfyre13** [comment] 2016-10-10 20:12
I had the same issue, writing up a pull request for it now. It's failing on an import of the python file for me at least, trying to `from MarkdownEditing.mde import *` isn't working because MarkdownEditing isn't in the PYTHONPATH. Local import works fine however, so adding a fallback on import error.

**Comment by felixhao28** [comment] 2016-10-11 09:38
Yes this is caused by incompatibility between ST2 and ST3. The fix is ready and will be released in the next version. But you need to be aware that I have not tested and will not guarantee any feature on ST2. So you are highly encouraged to switch to ST3.

**Comment by michou** [comment] 2016-10-12 17:41
@felixhao28 given that new releases aren't guaranteed to work on ST2 and the upgrade to ST3 is rather pricey, would it be an option to have two releases (or maybe two versions) of the plugin, one for ST2 and one for ST3? I would rather have no new features and a stable plugin rather than new features with the risk of some things breaking rather badly because they are not tested.

**Comment by felixhao28** [comment] 2016-10-13 03:05
@michou I see I will keep ST2 on my mind while doing further development. Thank you.

**Closed** 2016-10-13 05:35 UTC
