### ISSUE TITLE
Sublime freeze whilst searching

### ISSUE THREAD

**Issue by IanCaunce** [SublimeText-Markdown/MarkdownEditing#315] opened 2015-12-23 10:36 UTC
Hi,

I have used this package for around 6 months without issue but recently it I have noticed that with this package enabled sublime will freeze whilst searching a large project with lots of files. 

Disabling the package eliminates the issue.

To eliminate conflicts between packages, I have disabled all other packages except `MarkdownEditing`  and sublime still freezes when searching, suggesting to me this package is at fault. 

I can't see any errors in the console.

**Comment by felixhao28** [comment] 2015-12-24 03:11
Confirmed. The cause is two `on_modified` callbacks will be called every time there is something new appended to the "Find Result" page. The two callbacks are located in:

1. footnotes.py -> MarkFootnotes
2. distraction_free_mode.py -> KeepCurrentLineCentered

I will try something to improve this. Thanks for reporting.

**Comment by felixhao28** [comment] 2015-12-24 03:53
Should be fixed in v2.1.5

**Closed** 2016-03-04 03:41 UTC
Labels: bug
