### ISSUE TITLE
Shift+F11 full-screen '```' extra padding

### ISSUE THREAD

**Issue by djdeo** [SublimeText-Markdown/MarkdownEditing#492] opened 2017-12-14 03:03 UTC
the ```code``` input shows extra padding in Shift+F11 full-screen window, please check this screenshot
https://github.com/djdeo/screenshots-for-issue/blob/master/subl_full_screen_issue.png

**Comment by felixhao28** [comment] 2018-02-05 03:27
Closing as duplicate of #349. More discussions can be had there.

**Closed by felixhao28** 2018-02-05 03:27 UTC
