### ISSUE TITLE
Don't override current color scheme

### ISSUE THREAD

**Issue by kklot** [SublimeText-Markdown/MarkdownEditing#567] opened 2019-08-19 12:29 UTC
Sorry if I am missing something, but when open markdown files, this package loads its own theme. How can we config that it just uses whatever the current color scheme is, not taking over the Sublime settings? Thanks.

**Comment by dark-nova** [comment] 2019-09-28 19:09
I encountered this too, when I installed the package today. Thankfully, you can override the theme yourself.

1. In `Preferences > Settings`, copy the line containing `"color_scheme"`. If you defined this on your `User` settings, copy that instead of `Default`.
2. In `Preferences > Package Settings > Markdown Editing > Markdown GFM Settings - User`, paste the line into the file. If the file is empty, ensure it's surrounded by curly braces, like:
```
{
    "color_scheme": "...",
}
```
3. Repeat the process with the other `User` settings as desired.

The changes should load live after saving.

**Comment by kklot** [comment] 2019-09-30 14:09
@dark-nova well that _is_ the problem actually, I do not want that every time  I change my theme (which happens almost every day), I need to do that for this package.

**Comment by warmdev** [comment] 2019-10-23 00:55
You can use `PackageResourceViewer` to edit the `bootstrap.py` file line 91 to be like this

```python
default_mde_scheme = sublime.load_settings('Preferences.sublime-settings').get('color_scheme')
```

This will force `MarkdownEditing` to use the global color scheme. If it does not work, try click `Package Settings > Markdown Editing > Change color scheme` and this will force the color scheme to reload.

**Comment by doneykoo** [comment] 2019-12-04 08:37
me too. It would be better to have settings / option that allow us not using the scheme of this package, and instead, use the ST default color scheme.

**Comment by mtsk** [comment] 2020-01-04 09:46
This package seems to also override the `highlight_line` setting to `false`. I had to copy my `"highlight_line": true` setting to the "Markdown GFM Settings - User" file.

**Comment by tobek** [comment] 2020-04-30 00:46
See my comment here https://github.com/SublimeText-Markdown/MarkdownEditing/issues/209#issuecomment-621546163 for a workaround for returning control of color scheme to your general sublime settings.

**Comment by joaociocca** [comment] 2020-05-23 01:42
damn... I tried everything on this and over at [#209 (comment)](https://github.com/SublimeText-Markdown/MarkdownEditing/issues/209#issuecomment-621546163), and nothing makes a README.md file I have revert the color scheme to my selected color scheme. From what I've seen over there, this plugin was abandoned? Is that it?

**Comment by tobek** [comment] 2020-05-23 02:14
For what it's worth, and I'm not really sure why, but I have multiple "Markdown" options when I go to set syntax highlighting for a file, and one of them still has the plugin's overridden colors, but the other appears to have all the functionality of the plugin but doesn't override my scheme and styles. Perhaps my approach made a duplicate of the plugin, one with my updates and one original as downloaded?

**Comment by kklot** [comment] 2020-05-23 12:35
I removed this package for a while and see this issue is still here :|, the above commit in my fork would do it, you can either install from that fork or using Package Resourve Viewer to edit that and remove all other settings as well.

**Comment by deathaxe** [comment] 2021-05-13 17:55
Next release will come with a change which keeps global color scheme by default and suggests those builtins optionally only.

**Closed** 2021-09-12 15:59 UTC
Labels: enhancement

**Comment by artk47** [comment] 2021-12-28 09:53
I wonder, if there is an option to make changes to default color scheme, or override some settings (like background color which is too dark and one want to bring a bit more contrast)?

**Comment by deathaxe** [comment] 2021-12-28 10:24
You can always create a sublime-color-scheme file in your _User_ package and add overrides.

The easiest way is probably to use the `PackageDev: Edit Current Color Scheme` command.
