### ISSUE TITLE
Multiline highlighting for bold/italics?

### ISSUE THREAD

**Issue by thvasilo** [SublimeText-Markdown/MarkdownEditing#477] opened 2017-09-28 11:16 UTC
Currently if we start a bold or italic annotation and insert a line break,
the highlighting will not work.

Would it be possible to have multi-line highlighting? It's a very common
use case when taking notes etc. and want to keep columns at 80/100 chars.

![image](https://user-images.githubusercontent.com/9048995/30963702-c2e64a76-a44e-11e7-90d1-9840b5f73acb.png)

**Comment by felixhao28** [comment] 2018-02-05 06:20
Closing it as a duplicate of #103

**Closed by felixhao28** 2018-02-05 06:20 UTC
