### ISSUE TITLE
I'm getting a message after installing this using Package Control in Sublime Text 3 Build 3143

### ISSUE THREAD

**Issue by kimthdr** [SublimeText-Markdown/MarkdownEditing#485] opened 2017-11-16 02:08 UTC
Error loading syntax file "Packages/Markdown/Markdown.sublime-syntax": Unable to read Packages/Markdown/Markdown.sublime-syntax

**Comment by felixhao28** [comment] 2017-11-27 07:17
The default Markdown package should be disabled to prevent conflicts (like this). The process should be automated but can you check your `Preferences->Settings` to see if Markdown is listed in "ignored_packages"?

**Comment by DmitryMyadzelets** [comment] 2017-12-20 16:49
The same issue. The default Markdown package is (automatically) disabled in `Preferences.sublime-settings`:
```json
{
    "ignored_packages":[
        "Markdown"
    ]
}
```

**Comment by felixhao28** [comment] 2017-12-21 09:56
Then try "View | Syntax | MarkdownEditing | Markdown GFM"

**Comment by houfengmz** [comment] 2018-01-08 09:17
just remove the "Markdown" in "ignored_packages"

**Comment by erikjoling** [comment] 2018-01-21 19:03
I also had this message. It might have to do with a markdown file currently being opened and using the default Mardown syntaxt.

**Comment by felixhao28** [comment] 2018-01-22 04:51
Definitely yes. The `Packages/Markdown/Markdown.sublime-syntax` file is exclusively used by the default Markdown syntax package, which should be disabled upon successful installation of MarkdownEditing. Sublime is known to save what syntax you last used on a file. So that's probably what causes the issue.

**Comment by l-gothberg** [comment] 2018-02-07 05:01
As noted by @erikjoling  :
This issue occurs when the package is installed when there is a markdown file currently open.  All that is needed to fix the problem is to save the markdown file, close it, quit sublime, then reopen the file.

**Comment by GerHobbelt** [comment] 2019-06-19 11:19
Ran into this thing today. The **key element** here is to **close all MarkDown flavored files you have open in Sublime 3**, then restart. 

If you don't close **all** of them, the error report dialog will re-appear every time you start Sublime.

**Comment by cheng470** [comment] 2020-03-12 10:12
> Ran into this thing today. The **key element** here is to **close all MarkDown flavored files you have open in Sublime 3**, then restart.
> 
> If you don't close **all** of them, the error report dialog will re-appear every time you start Sublime.

It work for me, thanks.

**Comment by grap3-fru1t** [comment] 2020-06-15 13:19
Closing all active files in Sublime also worked for me to get rid of the re-appearing errors. 

My initial issue was a white theme background for .txt files that was apparently also caused by the "MarkdownEditing" package. After putting it to the ignore package -list, as suggested by the answer [here](https://stackoverflow.com/questions/62387136/theme-for-text-files-in-sublime-text-3), the error started popping up on every sublime start.

**Comment by davidhcefx** [comment] 2021-03-20 15:08
What a strange issue. The [Troubleshooting](https://github.com/SublimeText-Markdown/MarkdownEditing#troubleshooting) in the README.md provide no help.

**Closed** 2021-09-12 15:59 UTC
Labels: bug, C: syntax
