### ISSUE TITLE
Incorrect syntax highlting when "if" appears in bash codeblocks (GFM flavour)

### ISSUE THREAD

**Issue by rfdparker** [SublimeText-Markdown/MarkdownEditing#295] opened 2015-07-21 17:54 UTC
When `if` appears in a bash codeblock it appears there is some special syntax highlighting which expects this to be followed a some point by `then`, and presumably ultimately `fi`.

This works great where a codeblock truly contains an `if` control structure.

However, where the letters `if` simply appear as part of a command, things go wrong.

The `if` is highlighted like would be in an `if` control structure, but after the codeblock ends (with a line containing ```) an unwanted orange highlight applies to the remainder of the file.

## Screenshots

Correct behaviour with an `if` control structure:
![image](https://cloud.githubusercontent.com/assets/1406757/8808243/5f568048-2fd9-11e5-8ddc-34b39b1d9ee1.png)

Unwanted behaviour where `if` appears in a command:
![image](https://cloud.githubusercontent.com/assets/1406757/8808266/859e8b92-2fd9-11e5-9418-819594bf9a61.png)

**Comment by felixhao28** [comment] 2015-07-28 02:20
duplicate #237

**Comment by maliayas** [comment] 2015-08-10 22:08
dupe of #221, too

**Closed by maliayas** 2015-08-10 22:08 UTC
Labels: duplicate
