### ISSUE TITLE
Error loading syntax file

### ISSUE THREAD

**Issue by cryarchy** [SublimeText-Markdown/MarkdownEditing#542] opened 2018-09-26 08:29 UTC
I just installed MarkdownEditing on my Sublime Text editor **Version 3.1.1, Build 3176** and I get the error:
```
Error loading syntax file "Packages/Markdown/Markdown.sublime-syntax": Unable to read Packages/Markdown/Markdown.sublime-syntax
```
Kindly advice on how to resolve this.

**Comment by fxbenard** [comment] 2018-09-27 08:15
Same issue

**Comment by felixhao28** [comment] 2018-10-09 02:02
Close it as a duplicate of #485

**Closed by felixhao28** 2018-10-09 02:02 UTC
