### ISSUE TITLE
All color schemes disappear

### ISSUE THREAD

**Issue by vongoh** [SublimeText-Markdown/MarkdownEditing#300] opened 2015-08-24 18:57 UTC
Today I opened up ST3, and the default grey color scheme for `.md` files is gone.  My local syntax color scheme is displaying for these files instead.

What I have tried:

- closed, reopened ST
- disabled MDE from Package Control - shut down ST - opened up ST - reenabled MDE
- uninstalled MDE from Package Control - shut down ST - opened up ST - reinstalled MDE
- changed my User Settings `color_scheme` value to each of the three color schemes

None of these have had any effect.  

The only other thing that happened in my ST immediately before I opened a markdown file and discovered this - was an update message from Package Control informing me that my HTML/CSS/JS Beautify package was updated.

Obviously correlation is not causation - however there is nothing else about my environment that has changed in any way since last night before I went to bed, when the color schemes were working fine.

FYI this has happened with MDE before.  The color schemes disappeared temporarily -but I do not recall how they came back.

**Comment by VladimirPlokhov** [comment] 2015-08-25 08:46
The same for me.

**Comment by felixhao28** [comment] 2015-08-27 02:35
Color scheme for markdown is controlled in the package settings. Can you check both Default and User version of `Preferences -> Package Settings -> Markdown Editing -> Markdown GFM Settings` and look for "color_scheme" option and see if they are correct?

**Comment by younes0** [comment] 2015-08-27 12:34
same for me, all color schemes set to
`"color_scheme": "Packages/MarkdownEditing/MarkdownEditor-Dark.tmTheme",`

**Comment by vongoh** [comment] 2015-08-27 16:05
Both of my package settings files for Markdown GFM are set:

`"color_scheme": "Packages/MarkdownEditing/MarkdownEditor.tmTheme",`

**Comment by apostrophedave** [comment] 2015-08-27 19:26
same here, not sure when it happened first. 
selecting `colour scheme forget for view` in the preferences menu sets it to the correct colour but only lasts as long as the file is open

**Comment by felixhao28** [comment] 2015-08-28 04:23
This seems to be a bug with package control. Does `View -> Syntax -> MarkdownEditing -> Markdown` fix it?

**Comment by vongoh** [comment] 2015-08-28 05:00
No - `View -> Syntax -> MarkdownEditing -> Markdown` has no effect.  Some additional info:

I just rebooted my machine and restarted ST3.   When I first opened up a `.md` file the grey color scheme was back!  .. however ..

Literally the next instant I got another message from Package Control opening in a tab - notifying me that 'Bracket Highlighter' plugin was updated.   As soon as I clicked back over to the markdown file tab ... the color scheme was gone again.   Looks like that correlation is getting stronger ..

**Comment by younes0** [comment] 2015-08-28 07:48
Okay so I disabled "Color Highlighter Package" and markdown color scheme was back

**Comment by younes0** [comment] 2015-08-28 07:49
See <https://github.com/Monnoroch/ColorHighlighter/issues/256>

**Comment by apostrophedave** [comment] 2015-08-28 09:14
disabling that works, thanks younes0!

**Comment by vongoh** [comment] 2015-08-28 23:56
This did it for me too, nice find!

Too bad about losing Color Highlighter.  Its a handy little plugin to have :(

**Comment by marcus-at-localhorst** [comment] 2015-08-29 09:13
Should have come here earlier! Thanks for finding this out.

**Comment by felixhao28** [comment] 2015-12-18 08:04
Let's close it since it is confirmed not to be something to fix from this side.

**Closed by felixhao28** 2015-12-18 08:04 UTC
